### PR TITLE
Adds compatibility with Android Gradle Plugin 8.0.

### PR DESCRIPTION
**Pull request by asaarnak**
Issue #31

### CODE REVIEW

**Comment by bruntzcreative** [comment]
Can we get this one through?

**Comment by Anders3byg** [comment]
Any updates on this?

**Comment by Sether701** [comment]
Seems fine. Can @pikaju merge and deploy it?

**Comment by vahellame** [comment]
@pikaju ping

**Comment by dickermoshe** [comment]
@pikaju ping

**Comment by JeffreyDeNeve** [comment]
@pikaju ping, changes look good, please merge

**Comment by mkelleherUSSA** [comment]
merge bruhz... merge.

**Comment by mkelleherUSSA** [comment]
@pikaju Thank you!

**Comment by xVemu** [comment]
I think the wrong version was uploaded to pub.dev. 
Artifact downloaded directly from pub doesn't include this pull request and also has wrong version: 2.2.1 instead of 2.3.0

**Pull request merged**
